name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "taiki-e/checkout-action@v1"
      - name: Install Protobuf Compiler and Musl GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler musl-tools musl-dev
      - name: Set Short Release Sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: "dtolnay/rust-toolchain@1.85"
        with:
          targets: "x86_64-unknown-linux-musl"
      - run: cargo build --release --all-features
      - uses: "ncipollo/release-action@v1"
        with:
          token: "${{ github.token }}"
          tag: "latest-${{ steps.vars.outputs.sha_short }}"
          prerelease: true
          name: "Development Build"
          replacesArtifacts: true
          artifacts: |
            config.toml
            LICENSE
            *.md
            ./target/x86_64-unknown-linux-musl/release/cosdata

